"""initial schema substations and lines

Revision ID: 5a5f9d26aa40
Revises: 
Create Date: 2026-05-23 21:32:46.233133

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a5f9d26aa40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('voltage_kv', sa.Float(), nullable=True),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('volt_snap', sa.Float(), nullable=True),
    sa.Column('cost_per_km', sa.Float(), nullable=True),
    sa.Column('replacement_cost_usd', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('flood_mean', sa.Float(), nullable=True),
    sa.Column('flood_max', sa.Float(), nullable=True),
    sa.Column('flood_p95', sa.Float(), nullable=True),
    sa.Column('im_flood', sa.Float(), nullable=True),
    sa.Column('im_seismic', sa.Float(), nullable=True),
    sa.Column('im_landslide', sa.Float(), nullable=True),
    sa.Column('im_wildfire', sa.Float(), nullable=True),
    sa.Column('im_lightning', sa.Float(), nullable=True),
    sa.Column('im_wind', sa.Float(), nullable=True),
    sa.Column('im_hail', sa.Float(), nullable=True),
    sa.Column('im_tornado', sa.Float(), nullable=True),
    sa.Column('im_fzg', sa.Float(), nullable=True),
    sa.Column('im_geomag', sa.Float(), nullable=True),
    sa.Column('edr_flood', sa.Float(), nullable=True),
    sa.Column('edr_seismic', sa.Float(), nullable=True),
    sa.Column('edr_landslide', sa.Float(), nullable=True),
    sa.Column('edr_wildfire', sa.Float(), nullable=True),
    sa.Column('edr_lightning', sa.Float(), nullable=True),
    sa.Column('edr_wind', sa.Float(), nullable=True),
    sa.Column('edr_hail', sa.Float(), nullable=True),
    sa.Column('edr_tornado', sa.Float(), nullable=True),
    sa.Column('edr_fzg', sa.Float(), nullable=True),
    sa.Column('edr_geomag', sa.Float(), nullable=True),
    sa.Column('eal_flood', sa.Float(), nullable=True),
    sa.Column('eal_seismic', sa.Float(), nullable=True),
    sa.Column('eal_landslide', sa.Float(), nullable=True),
    sa.Column('eal_wildfire', sa.Float(), nullable=True),
    sa.Column('eal_lightning', sa.Float(), nullable=True),
    sa.Column('eal_wind', sa.Float(), nullable=True),
    sa.Column('eal_hail', sa.Float(), nullable=True),
    sa.Column('eal_tornado', sa.Float(), nullable=True),
    sa.Column('eal_fzg', sa.Float(), nullable=True),
    sa.Column('eal_geomag', sa.Float(), nullable=True),
    sa.Column('ead_flood', sa.Float(), nullable=True),
    sa.Column('ead_seismic', sa.Float(), nullable=True),
    sa.Column('ead_landslide', sa.Float(), nullable=True),
    sa.Column('ead_wildfire', sa.Float(), nullable=True),
    sa.Column('ead_lightning', sa.Float(), nullable=True),
    sa.Column('ead_wind', sa.Float(), nullable=True),
    sa.Column('ead_hail', sa.Float(), nullable=True),
    sa.Column('ead_tornado', sa.Float(), nullable=True),
    sa.Column('ead_fzg', sa.Float(), nullable=True),
    sa.Column('ead_geomag', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_lines_ead_flood'), 'lines', ['ead_flood'], unique=False)
    op.create_index(op.f('ix_lines_ead_fzg'), 'lines', ['ead_fzg'], unique=False)
    op.create_index(op.f('ix_lines_ead_geomag'), 'lines', ['ead_geomag'], unique=False)
    op.create_index(op.f('ix_lines_ead_hail'), 'lines', ['ead_hail'], unique=False)
    op.create_index(op.f('ix_lines_ead_landslide'), 'lines', ['ead_landslide'], unique=False)
    op.create_index(op.f('ix_lines_ead_lightning'), 'lines', ['ead_lightning'], unique=False)
    op.create_index(op.f('ix_lines_ead_seismic'), 'lines', ['ead_seismic'], unique=False)
    op.create_index(op.f('ix_lines_ead_tornado'), 'lines', ['ead_tornado'], unique=False)
    op.create_index(op.f('ix_lines_ead_wildfire'), 'lines', ['ead_wildfire'], unique=False)
    op.create_index(op.f('ix_lines_ead_wind'), 'lines', ['ead_wind'], unique=False)
    op.create_index(op.f('ix_lines_edr_flood'), 'lines', ['edr_flood'], unique=False)
    op.create_index(op.f('ix_lines_edr_fzg'), 'lines', ['edr_fzg'], unique=False)
    op.create_index(op.f('ix_lines_edr_geomag'), 'lines', ['edr_geomag'], unique=False)
    op.create_index(op.f('ix_lines_edr_hail'), 'lines', ['edr_hail'], unique=False)
    op.create_index(op.f('ix_lines_edr_landslide'), 'lines', ['edr_landslide'], unique=False)
    op.create_index(op.f('ix_lines_edr_lightning'), 'lines', ['edr_lightning'], unique=False)
    op.create_index(op.f('ix_lines_edr_seismic'), 'lines', ['edr_seismic'], unique=False)
    op.create_index(op.f('ix_lines_edr_tornado'), 'lines', ['edr_tornado'], unique=False)
    op.create_index(op.f('ix_lines_edr_wildfire'), 'lines', ['edr_wildfire'], unique=False)
    op.create_index(op.f('ix_lines_edr_wind'), 'lines', ['edr_wind'], unique=False)
    op.create_index(op.f('ix_lines_volt_snap'), 'lines', ['volt_snap'], unique=False)
    op.create_table('substations',
    sa.Column('ss_id', sa.String(), nullable=False),
    sa.Column('ss_name', sa.String(), nullable=True),
    sa.Column('ss_operator', sa.String(), nullable=True),
    sa.Column('ss_voltage', sa.String(), nullable=True),
    sa.Column('max_voltage_kv', sa.Integer(), nullable=True),
    sa.Column('ss_type', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('connected_tl_id', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('max_line_volt_kv', sa.Float(), nullable=True),
    sa.Column('volt_snap', sa.Float(), nullable=True),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('replacement_cost_usd', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('flood_depth_m', sa.Float(), nullable=True),
    sa.Column('pga_475', sa.Float(), nullable=True),
    sa.Column('ls_n10', sa.Float(), nullable=True),
    sa.Column('ls_lw', sa.Float(), nullable=True),
    sa.Column('ls_susc', sa.Float(), nullable=True),
    sa.Column('whp_cnt', sa.Float(), nullable=True),
    sa.Column('whp_cls', sa.Integer(), nullable=True),
    sa.Column('ltng_rate', sa.Float(), nullable=True),
    sa.Column('pe_1pct_maxwind_ms', sa.Float(), nullable=True),
    sa.Column('pe_2pct_maxwind_ms', sa.Float(), nullable=True),
    sa.Column('pe_5pct_maxwind_ms', sa.Float(), nullable=True),
    sa.Column('hail_rate', sa.Float(), nullable=True),
    sa.Column('hail_maxmag', sa.Float(), nullable=True),
    sa.Column('total_hits', sa.Integer(), nullable=True),
    sa.Column('ef2plus_hits', sa.Integer(), nullable=True),
    sa.Column('tornado_max_mag', sa.Integer(), nullable=True),
    sa.Column('annual_hit_rate', sa.Float(), nullable=True),
    sa.Column('annual_ef2plus_rate', sa.Float(), nullable=True),
    sa.Column('fzg_r_50rp', sa.Float(), nullable=True),
    sa.Column('fzg_g_50rp', sa.Float(), nullable=True),
    sa.Column('fzg_spi_50rp', sa.Float(), nullable=True),
    sa.Column('fzg_stusps', sa.String(), nullable=True),
    sa.Column('im_flood', sa.Float(), nullable=True),
    sa.Column('im_seismic', sa.Float(), nullable=True),
    sa.Column('im_landslide', sa.Float(), nullable=True),
    sa.Column('im_wildfire', sa.Float(), nullable=True),
    sa.Column('im_lightning', sa.Float(), nullable=True),
    sa.Column('im_wind', sa.Float(), nullable=True),
    sa.Column('im_hail', sa.Float(), nullable=True),
    sa.Column('im_tornado', sa.Float(), nullable=True),
    sa.Column('im_fzg', sa.Float(), nullable=True),
    sa.Column('edr_flood', sa.Float(), nullable=True),
    sa.Column('edr_seismic', sa.Float(), nullable=True),
    sa.Column('edr_landslide', sa.Float(), nullable=True),
    sa.Column('edr_wildfire', sa.Float(), nullable=True),
    sa.Column('edr_lightning', sa.Float(), nullable=True),
    sa.Column('edr_wind', sa.Float(), nullable=True),
    sa.Column('edr_hail', sa.Float(), nullable=True),
    sa.Column('edr_tornado', sa.Float(), nullable=True),
    sa.Column('edr_fzg', sa.Float(), nullable=True),
    sa.Column('edr_geomag', sa.Float(), nullable=True),
    sa.Column('eal_flood', sa.Float(), nullable=True),
    sa.Column('eal_seismic', sa.Float(), nullable=True),
    sa.Column('eal_landslide', sa.Float(), nullable=True),
    sa.Column('eal_wildfire', sa.Float(), nullable=True),
    sa.Column('eal_lightning', sa.Float(), nullable=True),
    sa.Column('eal_wind', sa.Float(), nullable=True),
    sa.Column('eal_hail', sa.Float(), nullable=True),
    sa.Column('eal_tornado', sa.Float(), nullable=True),
    sa.Column('eal_fzg', sa.Float(), nullable=True),
    sa.Column('ead_flood', sa.Float(), nullable=True),
    sa.Column('ead_seismic', sa.Float(), nullable=True),
    sa.Column('ead_landslide', sa.Float(), nullable=True),
    sa.Column('ead_wildfire', sa.Float(), nullable=True),
    sa.Column('ead_lightning', sa.Float(), nullable=True),
    sa.Column('ead_wind', sa.Float(), nullable=True),
    sa.Column('ead_hail', sa.Float(), nullable=True),
    sa.Column('ead_tornado', sa.Float(), nullable=True),
    sa.Column('ead_fzg', sa.Float(), nullable=True),
    sa.Column('ead_geomag', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ss_id')
    )
    op.create_index(op.f('ix_substations_asset_class'), 'substations', ['asset_class'], unique=False)
    op.create_index(op.f('ix_substations_ead_flood'), 'substations', ['ead_flood'], unique=False)
    op.create_index(op.f('ix_substations_ead_fzg'), 'substations', ['ead_fzg'], unique=False)
    op.create_index(op.f('ix_substations_ead_geomag'), 'substations', ['ead_geomag'], unique=False)
    op.create_index(op.f('ix_substations_ead_hail'), 'substations', ['ead_hail'], unique=False)
    op.create_index(op.f('ix_substations_ead_landslide'), 'substations', ['ead_landslide'], unique=False)
    op.create_index(op.f('ix_substations_ead_lightning'), 'substations', ['ead_lightning'], unique=False)
    op.create_index(op.f('ix_substations_ead_seismic'), 'substations', ['ead_seismic'], unique=False)
    op.create_index(op.f('ix_substations_ead_tornado'), 'substations', ['ead_tornado'], unique=False)
    op.create_index(op.f('ix_substations_ead_wildfire'), 'substations', ['ead_wildfire'], unique=False)
    op.create_index(op.f('ix_substations_ead_wind'), 'substations', ['ead_wind'], unique=False)
    op.create_index(op.f('ix_substations_edr_flood'), 'substations', ['edr_flood'], unique=False)
    op.create_index(op.f('ix_substations_edr_fzg'), 'substations', ['edr_fzg'], unique=False)
    op.create_index(op.f('ix_substations_edr_geomag'), 'substations', ['edr_geomag'], unique=False)
    op.create_index(op.f('ix_substations_edr_hail'), 'substations', ['edr_hail'], unique=False)
    op.create_index(op.f('ix_substations_edr_landslide'), 'substations', ['edr_landslide'], unique=False)
    op.create_index(op.f('ix_substations_edr_lightning'), 'substations', ['edr_lightning'], unique=False)
    op.create_index(op.f('ix_substations_edr_seismic'), 'substations', ['edr_seismic'], unique=False)
    op.create_index(op.f('ix_substations_edr_tornado'), 'substations', ['edr_tornado'], unique=False)
    op.create_index(op.f('ix_substations_edr_wildfire'), 'substations', ['edr_wildfire'], unique=False)
    op.create_index(op.f('ix_substations_edr_wind'), 'substations', ['edr_wind'], unique=False)
    op.create_index(op.f('ix_substations_max_voltage_kv'), 'substations', ['max_voltage_kv'], unique=False)
    op.create_index(op.f('ix_substations_region'), 'substations', ['region'], unique=False)
    op.create_index(op.f('ix_substations_region_id'), 'substations', ['region_id'], unique=False)
    op.create_index(op.f('ix_substations_volt_snap'), 'substations', ['volt_snap'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_substations_volt_snap'), table_name='substations')
    op.drop_index(op.f('ix_substations_region_id'), table_name='substations')
    op.drop_index(op.f('ix_substations_region'), table_name='substations')
    op.drop_index(op.f('ix_substations_max_voltage_kv'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_wind'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_wildfire'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_tornado'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_seismic'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_lightning'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_landslide'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_hail'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_geomag'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_fzg'), table_name='substations')
    op.drop_index(op.f('ix_substations_edr_flood'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_wind'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_wildfire'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_tornado'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_seismic'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_lightning'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_landslide'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_hail'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_geomag'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_fzg'), table_name='substations')
    op.drop_index(op.f('ix_substations_ead_flood'), table_name='substations')
    op.drop_index(op.f('ix_substations_asset_class'), table_name='substations')
    op.drop_table('substations')
    op.drop_index(op.f('ix_lines_volt_snap'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_wind'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_wildfire'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_tornado'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_seismic'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_lightning'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_landslide'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_hail'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_geomag'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_fzg'), table_name='lines')
    op.drop_index(op.f('ix_lines_edr_flood'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_wind'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_wildfire'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_tornado'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_seismic'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_lightning'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_landslide'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_hail'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_geomag'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_fzg'), table_name='lines')
    op.drop_index(op.f('ix_lines_ead_flood'), table_name='lines')
    op.drop_table('lines')
    # ### end Alembic commands ###
