// Role: raster intensity legend — shows colormap gradient + value range for the active hazard overlay
// Author: Dennies Bor
// Description: fetches /rasters/{rasterKey}.json (generated by build_rasters.py) and renders
//   a horizontal gradient bar with labeled ticks at vmin, mid, vmax and the units string.

import { useState, useEffect } from "react";
import { RASTER_HAZARDS } from "../../lib/constants.js";

function fmtVal(v) {
  if (v === 0) return "0";
  if (Math.abs(v) >= 10000) return (v / 1000).toFixed(0) + "k";
  if (Math.abs(v) >= 1000) return v.toFixed(0);
  if (Math.abs(v) >= 100) return v.toFixed(0);
  if (Math.abs(v) >= 10) return v.toFixed(1);
  if (Math.abs(v) >= 1) return v.toFixed(1);
  if (Math.abs(v) >= 0.1) return v.toFixed(2);
  return v.toExponential(1);
}

export default function RasterLegend({ hazard, rasterKey, showRaster }) {
  const [meta, setMeta] = useState(null);

  useEffect(() => {
    if (!hazard || !RASTER_HAZARDS.has(hazard) || !showRaster) {
      setMeta(null);
      return;
    }
    const key = rasterKey ?? hazard;
    fetch(`/rasters/${key}.json`)
      .then((r) => r.ok ? r.json() : null)
      .then(setMeta)
      .catch(() => setMeta(null));
  }, [hazard, rasterKey, showRaster]);

  if (!meta || !showRaster || !meta.gradient_stops) return null;

  const { vmin, vmax, units, norm, gradient_stops } = meta;
  const gradient = `linear-gradient(to right, ${gradient_stops.join(", ")})`;

  // Mid-point: geometric mean for log scales, arithmetic for linear.
  const mid = norm === "log" ? Math.sqrt(vmin * vmax) : (vmin + vmax) / 2;

  // Extract a short unit suffix from the full units string (first parenthesised group or fallback).
  const unitMatch = units.match(/\(([^)]+)\)/);
  const unitSuffix = unitMatch ? unitMatch[1] : units.split(",")[0].trim();

  return (
    <div className="absolute bottom-4 left-4 z-10 bg-white border border-line rounded-lg shadow-md px-3 pt-2 pb-2.5 w-52">
      <div className="text-[10px] font-semibold uppercase tracking-widest text-ink-muted mb-1.5 leading-tight">
        {unitSuffix}
      </div>

      {/* gradient bar */}
      <div className="h-2.5 rounded-sm w-full" style={{ background: gradient }} />

      {/* tick labels */}
      <div className="flex justify-between mt-1">
        <span className="text-[10px] text-ink-muted">{fmtVal(vmin)}</span>
        <span className="text-[10px] text-ink-muted">{fmtVal(mid)}</span>
        <span className="text-[10px] text-ink-muted">≥{fmtVal(vmax)}</span>
      </div>
    </div>
  );
}
